// Captures every gallery frame as a PNG + a per-flow contact sheet + an index,
// into review/, so the screens can be reviewed by people or other AIs without
// running anything. Run after `npm run build:gallery`:
//   npm run capture:gallery
// Needs a Chromium; set CHROMIUM_PATH if it isn't at the default below.
import { chromium } from 'playwright-core'
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { resolve } from 'node:path'

const SRC = resolve('dist-gallery/twoagree-screens.html')
const OUT = resolve('review')
const CHROMIUM = process.env.CHROMIUM_PATH ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome'
const REPO_RAW = 'https://raw.githubusercontent.com/alphadavid99/TwoAgree'
const BRANCH = process.env.REVIEW_BRANCH ?? 'claude/blissful-edison-aby3e9'

rmSync(OUT, { recursive: true, force: true })
mkdirSync(`${OUT}/screens`, { recursive: true })
mkdirSync(`${OUT}/full`, { recursive: true })
mkdirSync(`${OUT}/sheets`, { recursive: true })
copyFileSync(SRC, `${OUT}/twoagree-screens.html`)

const browser = await chromium.launch({ executablePath: CHROMIUM })
const page = await browser.newPage({ viewport: { width: 1800, height: 1000 } })
await page.goto(pathToFileURL(SRC).href + '?all=1')
await page.waitForFunction(
  () => [...document.querySelectorAll('.gframe')].every((f) => f.dataset.gready !== 'false'),
  null,
  { timeout: 120_000 },
)
await page.waitForTimeout(1000)
// The sticky gallery header would overlap element screenshots.
await page.addStyleTag({ content: '.ghead{position:static!important}' })

const meta = await page.evaluate(() =>
  [...document.querySelectorAll('.gflow')]
    .filter((s) => s.id.startsWith('flow-'))
    .map((s) => ({
      flow: s.id.slice(5),
      title: s.querySelector('h2').textContent,
      frames: [...s.querySelectorAll('.gcell')].map((c) => ({
        id: c.id.slice(2),
        num: c.querySelector('.gnum').textContent,
        title: c.querySelector('.gtitle').textContent,
        note: c.querySelector('.gnote')?.textContent ?? '',
        unrenderable: c.querySelector('.gnorender span')?.textContent ?? '',
      })),
    })),
)

for (const flow of meta) {
  for (const f of flow.frames) {
    if (f.unrenderable) continue
    const el = await page.$(`.gframe[data-frame="${f.id}"]`)
    f.png = `screens/${f.num}-${f.id}.png`
    await el.screenshot({ path: `${OUT}/${f.png}` })
    // Long screens: also capture the whole scroll length (fixed nav ends up at the bottom).
    const tall = await el.evaluate((n) => n.scrollHeight > n.clientHeight + 4)
    if (tall) {
      const prev = await el.evaluate((n) => {
        const s = { h: n.style.height, t: n.scrollTop }
        n.scrollTop = 0
        n.style.height = n.scrollHeight + 'px'
        return s
      })
      f.full = `full/${f.num}-${f.id}.png`
      await el.screenshot({ path: `${OUT}/${f.full}` })
      await el.evaluate((n, s) => { n.style.height = s.h; n.scrollTop = s.t }, prev)
    }
  }
  // Contact sheet: the flow's section as it appears in the gallery.
  flow.sheet = `sheets/${flow.flow}.png`
  await (await page.$(`#flow-${flow.flow}`)).screenshot({ path: `${OUT}/${flow.sheet}` })
}
await browser.close()

writeFileSync(`${OUT}/screens.json`, JSON.stringify(meta, null, 2))

const raw = (p) => `${REPO_RAW}/${BRANCH}/review/${p}`
const lines = [
  '# TwoAgree: every screen, for design review',
  '',
  'Generated by `npm run capture:gallery` from the dev-only screen gallery (`src/gallery`).',
  'Each screen is the real app component in a 390×844 phone frame, driven by fictional',
  'fixture data ("Sarah/Judah Placeholder"); nothing here is a real user. Fonts: Fraunces',
  '(display) and Hanken Grotesk (UI), as shipped.',
  '',
  `- Interactive version (tap through any screen): [twoagree-screens.html](https://raw.githack.com/alphadavid99/TwoAgree/${BRANCH}/review/twoagree-screens.html)`,
  '- Machine-readable index: [screens.json](screens.json)',
  '- `screens/` = what the phone shows; `full/` = the whole scroll length of long screens.',
  '',
  'Brand rules a reviewer should know: identity colour Claret `#3E1A2E`; honey `#E5A93C`',
  'is the action colour; app screens sit on a soft blush ground with white cards; the logo',
  'mark replaces the "A" in TwoAgree. Tone is calm, devotional, collaborative; no',
  'gamification, no "you vs them".',
  '',
]
for (const flow of meta) {
  lines.push(`## ${flow.title}`, '', `![${flow.title}](${raw(flow.sheet)})`, '')
  lines.push('| # | Screen | Image | Notes |', '|---|---|---|---|')
  for (const f of flow.frames) {
    const img = f.unrenderable
      ? '(not rendered)'
      : `[screen](${raw(f.png)})${f.full ? ` · [full length](${raw(f.full)})` : ''}`
    lines.push(`| ${f.num} | ${f.title} | ${img} | ${(f.unrenderable || f.note).replace(/\|/g, '/')} |`)
  }
  lines.push('')
}
writeFileSync(`${OUT}/README.md`, lines.join('\n'))
const n = meta.flatMap((f) => f.frames).filter((f) => f.png).length
console.log(`capture-gallery: ${n} screens, ${meta.length} contact sheets → review/`)
